# Width of a tab character.  Setting it high so it's obvious when I have one.
set global tabstop 8
# Width of indentation using `>` and `<`.
set global indentwidth 2
# When saving, write to a new file, then replace the existing one with it.
set global writemethod replace

hook global ModuleLoaded smarttab %{
  set-option global softtabstop 4
}

hook global BufOpenFile .* expandtab
hook global BufNewFile .* expandtab

eval %sh{kak-lsp --kakoune -s $kak_session}

hook global WinSetOption filetype=(haskell) %{
  lsp-enable-window
}

map global user l %{: enter-user-mode lsp<ret>} -docstring "LSP mode"

# Copy/paste X primary selection.
map global user p '<a-!>xsel -op<ret>' -docstring "Append X primary selection"
map global user P '!xsel -op<ret>' -docstring "Insert X primary selection"
map global user R 'd!xsel -op<ret>' -docstring "Replace with X primary selection"
map global user y '<a-|>xsel -ip<ret>' -docstring "Set as X primary selection" 
map global user v 'i<ret><esc>h!xsel -op<ret>uUyup' -docstring "Append X primary selection lines"
map global user V 'i<ret><esc>h!xsel -op<ret>uUyuP' -docstring "Insert X primary selection lines"

declare-user-mode clipboard
map global clipboard p '<a-!>xsel -ob<ret>' -docstring "Append X clipboard selection"
map global clipboard P '!xsel -ob<ret>' -docstring "Insert X clipboard selection"
map global clipboard R 'd!xsel -ob<ret>' -docstring "Replace with X clipboard selection"
map global clipboard y '<a-|>xsel -ib<ret>' -docstring "Set as X clipboard selection" 
map global clipboard v 'i<ret><esc>h!xsel -ob<ret>uUyup' -docstring "Append X clipboard selection lines"
map global clipboard V 'i<ret><esc>h!xsel -ob<ret>uUyuP' -docstring "Insert X clipboard selection lines"

map global user c %{: enter-user-mode clipboard<ret>} -docstring "Clipboard mode"
